### ISSUE TITLE
Support for an extra md file

### ISSUE THREAD

**Issue by orschiro** [chibicode/solo#13]
Dear @chibicode,

Thank you very much for your simple theme! I know you explicitly say that this theme only supports one single md file. However, I am wondering what I have to modify in order to add support for a second md file. 

I use your theme to display my [index.md](http://robert.orzanna.de/). I created a duplicate of that file and named it [rss.md](http://robert.orzanna.de/rss/). It uses the same default layout. But as you can see, it does not display the content properly. 
- My index.md on Github: https://github.com/orschiro/robert.orzanna.de/blob/gh-pages/index.md
- My rss.md on Github: https://github.com/orschiro/robert.orzanna.de/blob/gh-pages/rss.md

I appreciate your response!

Warmly,

Robert

**Comment by rzblue** [comment]
But the point of this theme is to _only_ have one page, you would be defeating the purpose.

**Comment by orschiro** [comment]
Dear @firecrafty,

I guess you're right here. 

Let's close this discussion since things have moved on my side. 

Warmly,

~Robert
