### ISSUE TITLE
first line of highlight starts with space

### ISSUE THREAD

**Issue by bquast** [chibicode/solo#7]
I love your theme and want to use it for an R package that I have designed. The page I am using is this one:

http://qua.st/decompr/

as you can see, in both cases the first line of the highlight block in indented with one space. Is there any way to remove this? I use the exact same code in a jekyll blog post (poole theme) and it does not have this issue, see: http://qua.st/ggvis-shiny-html5-slides/.

Lastly, is there any way to change the font size of the highlighting? my lines are just a little bit to long as you can. not an issue, just a question.

thanks again, I love this theme and hope to use it many times!!

**Comment by chibicode** [comment]
> in both cases the first line of the highlight block in indented with one space. Is there any way to remove this?

I think I just fixed it with https://github.com/chibicode/solo/commit/920ea8410a6da97cc0762d0af8b0dbe37a13888b - check out the CSS changes. Sorry for the bug. I also made the font size for the code block smaller.

**Comment by bquast** [comment]
this is perfect, thanks a lot
