### ISSUE TITLE
index.md

### ISSUE THREAD

**Issue by lyndell** [chibicode/solo#8]
I think the `index.md` should be in the root directory, not the `_include` directory.  It'd be more intutive and better seperate content from presentation.

**Comment by chibicode** [comment]
@lyndell yup, it's done by this PR: https://github.com/chibicode/solo/pull/9 Thanks!

**Comment by lyndell** [comment]
Cool.  Usage in index.md still says, "_includes/index.md."

**Comment by chibicode** [comment]
@lyndell fixed! thanks!
